### ISSUE TITLE
have you considered contributing to scanpy?

### ISSUE THREAD

**Issue by fidelram** [harbourlab/PieParty#1]
I just noticed your paper and thought that PieParty could be a nice addition to scanpy (http://scanpy.readthedocs.io/) plotting.  Would be nice to add your code to https://github.com/theislab/scanpy/blob/master/scanpy/plotting/_tools/scatterplots.py#L48

**Comment by harbourlab** [comment]
Thank you! We will look into it once the tool is developed a bit further!
