### ISSUE TITLE
Interpreting the output image

### ISSUE THREAD

**Issue by thugib** [harbourlab/PieParty#2]
Hi creators of PieParty,
     This is very creative and I think could be be very helpful to us, but I just wanted to get a few things straight before presenting it to others.  I have included a .png image. There is a list of five genes on the image which are in the order of my gene_list.csv file.
![PieParty_closeup2](https://user-images.githubusercontent.com/253391/92980163-146f4e80-f463-11ea-898e-bcd211f31df1.png)

   I am not quite sure about how to interpret the image. So, the top left corner has a cell with a little more than 50% dark purple, which I am guessing the dark purple pie piece represents WOX5, the first gene on my list. On this same cell, there is a very small lavender color pie piece and three other pieces that go from dark green-blue to light-green. Again I am assuming that going counter-clockwise on this cell the lavendar (dark grey ?) color pie piece would be JKD, the dark green-blue is SCR, the green BBM/PLT1 and the light green is PLT1. 

  However, there is a cell covering  (on top of) this upermost leftmost cell, and it has 4 sections. I am not quite sure which genes each of these four pie pieces in this cell represent. There is a large blue piece and a light blue piece and a grey peice.  Also, what is the pink color representing ?  

   Are the genes in order as you clockwise or counter-clockwise around the pie ?  There is a cell just below and to the right of the gene list. In this case, there is a greyish color on top and pink clockwise and a bluish-green counter-clockwise. I would guess the pink may be WOX5, but low concentration. This same cell also does not seem to have the green piece; just the light green. There seems to be a white piece in place of the green piece. Does that mean there is no of the green gene or just very low concentration of the green gene, which I am assuming is BBM/PLT4.

  Sorry for all the questions, but I just want to be able to answer any questions I get when I present the data to others.

**Comment by harbourlab** [comment]
I will get back to you this weekend!

**Comment by harbourlab** [comment]
Could you please provide the exact command you use to execute PieParty?

**Comment by thugib** [comment]
This is the command:

matthew@OptiPlex-7071:~/python/PieParty-master$ python3 PieParty.py -g 
/home/matthew/python/ABCpm_anchored_dcX30_resp5_geneexp.csv -c 
/home/matthew/python/ABCpm_anchored_dcX30_resp5_cellcoord.csv -l 
/home/matthew/python/QC5.csv

And this is the output:

PieParty Version 1.3 starting
Done calculating! Baking the pies now.
/home/matthew/.local/lib/python3.6/site-packages/PIL/Image.py:2835: 
DecompressionBombWarning: Image size (169000000 pixels) exceeds limit of 
89478485 pixels, could be decompression bomb DOS attack.
   DecompressionBombWarning,
1882 cells plotted

Matthew

**Comment by harbourlab** [comment]
Thanks! I'm working on it. I'll have a new version uploaded tomorrow which will plot a legend, so that you know which gene is what. The pink is indeed a bug, which i need to fix. There should not be a pink - seems to be a thing when small gene lists are plotted. (Edit: The pink color is actually correct, see below)

**Comment by thugib** [comment]
OK. Thank you very much for your help. I was thinking that maybe I could 
just put one gene in a list and do multiple lists and specify a color 
for each list.

Matthew

**Comment by harbourlab** [comment]
Alright, I did some checking and the pink is actually correct. The dark blue the "viridis" color scale starts with is actually a dark pink, which turns really pink when brightened. I will upload a new version of PieParty in a minute (version 1.5), which will now generate a "labels.svg" output file, explaining the output.

Your input was very valuable, and I'm still working on adding some more features to PieParty. Please let me know if you have any more questions or run into problems. Also if you are missing a feature that would be helpful for your work please let me know!

**Comment by thugib** [comment]
Thank you very much for your help.

I thought of one thing that may be helpful. I always get the following 
warning when I run PieParty.py:

/home/matthew/.local/lib/python3.6/site-packages/PIL/Image.py:2835: 
DecompressionBombWarning: Image size (169000000 pixels) exceeds limit of 
89478485 pixels, could be decompression bomb DOS attack.
   DecompressionBombWarning,

     I thought it may be helpful to warn people that this message may 
come up and to ignore it if it does. The message may scare some people 
away from using PieParty.

Matthew

**Comment by harbourlab** [comment]
Very true! The new version will output an explainer.. I will put one on the github site too. Thanks!! Let me know if everything works for you!
